import { Schema } from "effect";

export const Ayanamsa = Schema.Literals([
  "FaganBradley",
  "Lahiri",
  "DeLuce",
  "Raman",
  "Ushashashi",
  "Krishnamurti",
  "DjwhalKhul",
  "Yukteshwar",
  "JNBhasin",
  "BabylKugler1",
  "BabylKugler2",
  "BabylKugler3",
  "BabylHuber",
  "BabylEtPSC",
  "Aldebaran15Tau",
  "Hipparchos",
  "Sassanian",
  "GalacticCenter0Sag",
  "J2000",
  "J1900",
  "B1950",
  "SuryaSiddhanta",
  "SuryaSiddhantaMeanSun",
  "Aryabhata",
  "AryabhataMeanSun",
  "SSRevati",
  "SSCitra",
  "TrueCitra",
  "TrueRevati",
  "TruePushya",
  "GalacticCenterGilBrand",
  "GalacticEquatorIAU1958",
  "GalacticEquator",
  "GalacticEquatorMidMula",
  "Skydram",
  "TrueMula",
  "DhruvaGalCenterMulaWilhelm",
  "Aryabhata522",
  "BabylBritton",
]);

export const HouseSystem = Schema.Literals([
  "Placidus",
  "Koch",
  "Porphyrius",
  "Regiomontanus",
  "Campanus",
  "Equal",
  "VehlowEqual",
  "WholeSign",
  "Meridian",
  "Azimuthal",
  "PolichPage",
  "Alcabitus",
  "Morinus",
]);

export class Options extends Schema.Class<Options>("AstroParams")({
  ayanamsa: Ayanamsa,
  houseSystem: HouseSystem,
}) {}
