import * as Swisseph from "@swisseph/node";

import { type Ayanamsa, type HouseSystem } from "../astro-params/model.js";
import { type CelestialBody } from "../ephemeris/model.js";

export const SIDEREAL_MODE: Record<typeof Ayanamsa.Type, Swisseph.SiderealMode> = {
  FaganBradley: Swisseph.SiderealMode.FaganBradley,
  Lahiri: Swisseph.SiderealMode.Lahiri,
  DeLuce: Swisseph.SiderealMode.DeLuce,
  Raman: Swisseph.SiderealMode.Raman,
  Ushashashi: Swisseph.SiderealMode.Ushashashi,
  Krishnamurti: Swisseph.SiderealMode.Krishnamurti,
  DjwhalKhul: Swisseph.SiderealMode.DjwhalKhul,
  Yukteshwar: Swisseph.SiderealMode.Yukteshwar,
  JNBhasin: Swisseph.SiderealMode.JNBhasin,
  BabylKugler1: Swisseph.SiderealMode.BabylKugler1,
  BabylKugler2: Swisseph.SiderealMode.BabylKugler2,
  BabylKugler3: Swisseph.SiderealMode.BabylKugler3,
  BabylHuber: Swisseph.SiderealMode.BabylHuber,
  BabylEtPSC: Swisseph.SiderealMode.BabylEtPSC,
  Aldebaran15Tau: Swisseph.SiderealMode.Aldebaran15Tau,
  Hipparchos: Swisseph.SiderealMode.Hipparchos,
  Sassanian: Swisseph.SiderealMode.Sassanian,
  GalacticCenter0Sag: Swisseph.SiderealMode.GalacticCenter0Sag,
  J2000: Swisseph.SiderealMode.J2000,
  J1900: Swisseph.SiderealMode.J1900,
  B1950: Swisseph.SiderealMode.B1950,
  SuryaSiddhanta: Swisseph.SiderealMode.SuryaSiddhanta,
  SuryaSiddhantaMeanSun: Swisseph.SiderealMode.SuryaSiddhantaMeanSun,
  Aryabhata: Swisseph.SiderealMode.Aryabhata,
  AryabhataMeanSun: Swisseph.SiderealMode.AryabhataMeanSun,
  SSRevati: Swisseph.SiderealMode.SSRevati,
  SSCitra: Swisseph.SiderealMode.SSCitra,
  TrueCitra: Swisseph.SiderealMode.TrueCitra,
  TrueRevati: Swisseph.SiderealMode.TrueRevati,
  TruePushya: Swisseph.SiderealMode.TruePushya,
  GalacticCenterGilBrand: Swisseph.SiderealMode.GalacticCenterGilBrand,
  GalacticEquatorIAU1958: Swisseph.SiderealMode.GalacticEquatorIAU1958,
  GalacticEquator: Swisseph.SiderealMode.GalacticEquator,
  GalacticEquatorMidMula: Swisseph.SiderealMode.GalacticEquatorMidMula,
  Skydram: Swisseph.SiderealMode.Skydram,
  TrueMula: Swisseph.SiderealMode.TrueMula,
  DhruvaGalCenterMulaWilhelm: Swisseph.SiderealMode.DhruvaGalCenterMulaWilhelm,
  Aryabhata522: Swisseph.SiderealMode.Aryabhata522,
  BabylBritton: Swisseph.SiderealMode.BabylBritton,
};

export const CELESTIAL_BODY: Record<CelestialBody, Swisseph.CelestialBody> = {
  Sun: Swisseph.Planet.Sun,
  Moon: Swisseph.Planet.Moon,
  Mars: Swisseph.Planet.Mars,
  Mercury: Swisseph.Planet.Mercury,
  Venus: Swisseph.Planet.Venus,
  Jupiter: Swisseph.Planet.Jupiter,
  Saturn: Swisseph.Planet.Saturn,
  TrueNode: Swisseph.LunarPoint.TrueNode,
};

export const HOUSE_SYSTEM: Record<typeof HouseSystem.Type, Swisseph.HouseSystem> = {
  Placidus: Swisseph.HouseSystem.Placidus,
  Koch: Swisseph.HouseSystem.Koch,
  Porphyrius: Swisseph.HouseSystem.Porphyrius,
  Regiomontanus: Swisseph.HouseSystem.Regiomontanus,
  Campanus: Swisseph.HouseSystem.Campanus,
  Equal: Swisseph.HouseSystem.Equal,
  VehlowEqual: Swisseph.HouseSystem.VehlowEqual,
  WholeSign: Swisseph.HouseSystem.WholeSign,
  Meridian: Swisseph.HouseSystem.Meridian,
  Azimuthal: Swisseph.HouseSystem.Azimuthal,
  PolichPage: Swisseph.HouseSystem.PolichPage,
  Alcabitus: Swisseph.HouseSystem.Alcabitus,
  Morinus: Swisseph.HouseSystem.Morinus,
};
